/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.view;

import co.edu.unicauca.domain.entities.User;
import co.edu.unicauca.domain.services.UserService;
import co.edu.unicauca.infra.Messages;
import co.edu.unicauca.interfaces.IFrameFactory;
import javax.swing.JFrame;

/**
 *
 * @author Brayan
 */
public class GUILogin extends javax.swing.JFrame {

    private UserService Service;
    private IFrameFactory frameFactory;

    public GUILogin(UserService service, IFrameFactory frame) {
        this.Service = service;
        this.frameFactory = frame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alwaysx
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        txtcontrasenia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtcontraseña = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Registrarse = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(39, 246, 249));
        setSize(new java.awt.Dimension(450, 380));
        getContentPane().setLayout(null);

        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        txtcontrasenia.setName(""); // NOI18N
        getContentPane().add(txtcontrasenia);
        txtcontrasenia.setBounds(140, 230, 184, 22);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 280, 176, 26);

        txtcontraseña.setName(""); // NOI18N
        getContentPane().add(txtcontraseña);
        txtcontraseña.setBounds(140, 190, 180, 22);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 38, 107));
        jLabel1.setText("Gestion de Proyectos Software");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 236, 19);

        jPanel1.setBackground(new java.awt.Color(242, 247, 249));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 359, 24, 171);

        jLabel6.setText("Olvido contraseña");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 310, 96, 16);

        Registrarse.setText("Registrarse");
        Registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarseMouseClicked(evt);
            }
        });
        getContentPane().add(Registrarse);
        Registrarse.setBounds(250, 310, 57, 16);

        jLabel5.setForeground(new java.awt.Color(242, 247, 249));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unicauca.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 40, 125, 151);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 230, 79, 22);

        jPanel2.setBackground(new java.awt.Color(242, 247, 249));
        jPanel2.setForeground(new java.awt.Color(192, 23, 23));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(190, 28, 168, 368);
        jPanel2.add(jLabel2, gridBagConstraints);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 450, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String contrasenia = txtcontrasenia.getText().trim();
        String usuario = txtcontraseña.getText().trim();
        User result = Service.login(usuario, contrasenia);
        if (result != null) {
            if (verifyPassword(contrasenia,result.getContrasenia() )) {
                JFrame instance = frameFactory.createFrame(result);
                instance.setExtendedState(JFrame.NORMAL);
                instance.setVisible(true);
                this.dispose();

            } else{
                Messages.showMessageDialog("Credenciales invalidad", "Atención");
            }
        } else {
            Messages.showMessageDialog("Usuario inexistenete", "Atención");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean verifyPassword(String rawPassword, String Passwordbd) {
        // Lógica para comparar hash
        return rawPassword.equals(Passwordbd);
    }
    private void RegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarseMouseClicked
        this.dispose();
        GUIRecordType instance = new GUIRecordType();
        instance.setExtendedState(JFrame.NORMAL);
        instance.setVisible(true);
    }//GEN-LAST:event_RegistrarseMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Registrarse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtcontrasenia;
    private javax.swing.JTextField txtcontraseña;
    // End of variables declaration//GEN-END:variables

}
