/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.view;

import co.edu.unicauca.access.Factory;
import co.edu.unicauca.domain.services.CompanyService;
import co.edu.unicauca.domain.services.StudentService;
import co.edu.unicauca.interfaces.IRepository;
import javax.swing.JFrame;

/**
 *
 * @author Yisus
 */
public class GUIRecordType extends javax.swing.JFrame {

    /**
     * Creates new form GUIRecordType
     */
    public GUIRecordType() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbltipoderegistro = new javax.swing.JLabel();
        lblenunciado = new javax.swing.JLabel();
        lbltiporegistro1 = new javax.swing.JLabel();
        cbxtipo = new javax.swing.JComboBox<>();
        btnvolver = new javax.swing.JButton();
        btnsiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(450, 380));

        jPanel1.setBackground(new java.awt.Color(242, 247, 249));
        jPanel1.setPreferredSize(new java.awt.Dimension(450, 380));

        lbltipoderegistro.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbltipoderegistro.setForeground(new java.awt.Color(35, 38, 107));
        lbltipoderegistro.setText("Tipo de Registro");

        lblenunciado.setBackground(new java.awt.Color(255, 255, 255));
        lblenunciado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblenunciado.setText("Por favor seleccione el tipo de resgitro deseado:");

        lbltiporegistro1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltiporegistro1.setForeground(new java.awt.Color(35, 38, 107));
        lbltiporegistro1.setText("Tipo");

        cbxtipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbxtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Empresa" }));
        cbxtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxtipoActionPerformed(evt);
            }
        });

        btnvolver.setBackground(new java.awt.Color(191, 212, 228));
        btnvolver.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(35, 38, 107));
        btnvolver.setText("Volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        btnsiguiente.setBackground(new java.awt.Color(13, 65, 133));
        btnsiguiente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnsiguiente.setForeground(new java.awt.Color(255, 255, 255));
        btnsiguiente.setText("Siguiente");
        btnsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lbltipoderegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblenunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lbltiporegistro1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cbxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnvolver)
                        .addGap(94, 94, 94)
                        .addComponent(btnsiguiente)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbltipoderegistro)
                .addGap(31, 31, 31)
                .addComponent(lblenunciado)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltiporegistro1)
                    .addComponent(cbxtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsiguiente)
                    .addComponent(btnvolver))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        String seleccionado = cbxtipo.getSelectedItem().toString();
        if (seleccionado.equals("Estudiante")) {
            //  IRepository serviceRepository = Factory.getInstance().getRepository("company");
            IRepository studentRepository = Factory.getInstance().getRepository("student");

            //   CompanyService servicecompany = new CompanyService(serviceRepository);
            StudentService servicestudent = new StudentService(studentRepository);

            GUIRegisterStudent instance = new GUIRegisterStudent(servicestudent);
            instance.setExtendedState(JFrame.MAXIMIZED_BOTH);
            instance.setSize(450, 380); // Ajusta el tamaño a 600x400 píxeles
            instance.setLocationRelativeTo(null); // Centrar en pantalla
            instance.setVisible(true);
        } else {
            IRepository CompanyRepository = Factory.getInstance().getRepository("company");

            //   CompanyService servicecompany = new CompanyService(serviceRepository);
            CompanyService servicecompany = new CompanyService(CompanyRepository);

            GUIRegistreCompany instance = new GUIRegistreCompany(servicecompany);
            instance.setExtendedState(JFrame.MAXIMIZED_BOTH);
            instance.setSize(450, 380); // Ajusta el tamaño a 600x400 píxeles
            instance.setLocationRelativeTo(null); // Centrar en pantalla
             instance.setVisible(true);
        }
    }//GEN-LAST:event_btnsiguienteActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        this.dispose();
        GUILogin instance = new GUILogin();
        instance.setExtendedState(JFrame.MAXIMIZED_BOTH);
        instance.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    private void cbxtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxtipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JButton btnvolver;
    private javax.swing.JComboBox<String> cbxtipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblenunciado;
    private javax.swing.JLabel lbltipoderegistro;
    private javax.swing.JLabel lbltiporegistro1;
    // End of variables declaration//GEN-END:variables
}
